spring:
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/ftl
  main:
    allow-bean-definition-overriding: true
    
logging:
  file: log/admin-opetra.log

server:
  port: 8086